export enum MyIcons {
    Account = "account",
    AccountOutlined = "account-outline",
    Earth = "earth",
    Eye = "eye",
    EyeOutlined = "eye-outline",
    EyeOff = "eye-off",
    EyeOffOutlined = "eye-off-outline",
    Login = "login",
    Logout = "logout",
    MoreVertical = "dots-vertical",
    RadioboxBlank = "radiobox-blank",
    RadioboxMarked = "radiobox-marked",
    Web = "web",
};
