export enum MyLocalizationTextKeys {
    CheckLoginInformation,
    Okey,
    ChangeLanguage,
    Turkish,
    English,
    Options,
    Login,
    Logout,
    Password,
    UserId,
    ServerAddress,
    AppCopyrightDescription,
    AppNameFull,
};
